### ISSUE TITLE
Channel Service Quirks

### ISSUE THREAD

**Issue by colesanders** [GetStream/stream-chat-angular#248]
While using this package to add chat functionality to an existing app I've ran into a couple of quirks/issues making the experience less than ideal. So far most of the drop in stuff has worked amazing right off the bat. Getting chat up and running in the app took very little, but tuning the fine grain details was more difficult.

## Active Channel

At roughly line 950 in the `channel.service.ts`
```typescript
  private async queryChannels() {
    try {
      const channels = await this.chatClientService.chatClient.queryChannels(
        this.filters!,
        this.sort,
        this.options
      );
      channels.forEach((c) => this.watchForChannelEvents(c));
      const prevChannels = this.channelsSubject.getValue() || [];
      this.channelsSubject.next([...prevChannels, ...channels]);
      if (channels.length > 0 && !this.activeChannelSubject.getValue()) {
        this.setAsActiveChannel(channels[0]);
      }
      this.hasMoreChannelsSubject.next(channels.length >= this.options!.limit!);
    } catch (error) {
      this.channelsSubject.error(error);
    }
  }
```
The section that sets the active channel as the first result means that initializing the channel service causes read events to fire on that channel. So when the chat sidebar isn't active in the app and the user isn't seeing the chat, the messages are marked read anyways. The obvious solution to that issue is to not initialize the chat until necessary, however then we can't listen to channel events and notify the user of new messages.
* _As a note there's also no way to clear the active channel without resetting the ChannelService._

## Channel Queries

Another issue I've ran into is the lack of a return value on `channelService.init()`. The regular stream-chat JS client returns the found channels when querying, but the angular one doesn't. Since the JS client returns the found channels, if the query is for a channel with a specific id, and no channels are returned we can use the empty result to warn the user that they don't have permission. This has lead to us using the following code to load channels and detect if a user is a member of the given channel:

```typescript
appendChannels(ids: string | string[]) {
    const arrIds = typeof ids === 'string' ? [ids] : ids;
    const query = {
      type: 'commerce',
      members: { $in: [this.activeUserId] },
      id: arrIds.length === 1 ? { $eq: arrIds[0] } : { $in: arrIds },
    };

    return combineLatest([
      from(this.channelService.init(query)),
      from(this.chatService.chatClient.queryChannels(query)),
    ]).pipe(
      switchMap(([, available]) =>
        iif(
          () => !available.length,
          defer(() => throwError({ error: new Error('User is not a member of this channel!'), channels: arrIds })),
          of(available)
        )
      ),
      map(channels => channels.find(channel => arrIds.some(id => id === channel.id))),
      tap(channel => channel && this.channelService.setAsActiveChannel(channel)),
      map(() => arrIds)
    );
  }
```

These weird pieces of the angular stream chat package make sense for it as a drop in solution, but when a developer needs more fine grain control of stream chat, it makes those changes much more difficult.

**Comment by szuperaz** [comment]
Thanks for your detailed feedback, we know our customizability is in an early stage so these feedbacks are really important for us.

All these problems seem valid to me so I added the following functionality to the `ChannelService`:
- The `init` method now returns the result of the channel query (and throws an error if any occurred)
- You can provide a flag to the `init` method to prevent setting an active channel
- There is a `deselectActiveChannel` method that can be used to deselect the currently active channel

These features are available in stream-chat-angular@2.21.0
