### ISSUE TITLE
Channel Preview component change detection

### ISSUE THREAD

**Issue by trentCareApp** [GetStream/stream-chat-angular#264]
When Person A messages Person B, but person B has a chat other than (A<->B) selected, the Channel preview of that conversation for person B will not show the latest message from A (expected), but instead the message prior to that.

This can be fixed for us in a custom channel preview component, by calling `changeDetectorRef.detectChanges` when a new message is received, in the `handleMessageEvent` or `setLatestMessage` methods

https://github.com/GetStream/stream-chat-angular/blob/8bfb6cdc2cd21f7a9ef762078d75a56267e56f3f/projects/stream-chat-angular/src/lib/channel-preview/channel-preview.component.ts#L129

The screenshot below shows two users, A & B talking to each other, where B has 'received' the new message, but has not updated the channel preview UI to reflect that.

![Screen Shot 2022-04-19 at 3 32 26 pm](https://user-images.githubusercontent.com/77595539/163936667-6e138ad1-3fdf-45cb-b2a6-3b6f170878dd.png)

**Comment by szuperaz** [comment]
Hi,

Is this problem occurs when using the default channel preview component?

This is the application I used for testing: https://github.com/GetStream/stream-chat-angular/tree/master/projects/sample-app and the problem didn't occur to me. Do you have a different set up?

The `handleMessageEvent` uses `ngZone.run` to reenter Angular's change detection zone: https://github.com/GetStream/stream-chat-angular/blob/8bfb6cdc2cd21f7a9ef762078d75a56267e56f3f/projects/stream-chat-angular/src/lib/channel-preview/channel-preview.component.ts#L112 - that should take care of the UI update.
