### ISSUE TITLE
BUG: Can't i18n label in channel-preview when there are no messages in channel

### ISSUE THREAD

**Issue by npalikuca** [GetStream/stream-chat-angular#265]
In `channel-preview.component.ts` when there are no messages then property `latestMessage` is set to `Nothing yet...`.
In related HTML template text is interpolated with `{{ latestMessage | translate }}`, but because prefix `streamChat` is not set then ngx-translate can't find translation by key. It should be `streamChat.Nothing yet...`.

https://github.com/GetStream/stream-chat-angular/blob/master/projects/stream-chat-angular/src/lib/channel-preview/channel-preview.component.ts#L29
https://github.com/GetStream/stream-chat-angular/blob/master/projects/stream-chat-angular/src/lib/channel-preview/channel-preview.component.ts#L114

Example:
https://github.com/GetStream/stream-chat-angular/blob/master/projects/stream-chat-angular/src/lib/channel-preview/channel-preview.component.ts#L131

Demo from console:
![This is an image](https://i.ibb.co/VL5X29b/get-stream-issue.png)

**Comment by szuperaz** [comment]
Thanks for reporting this bug, it is now fixed in version 3.2.2.
