### ISSUE TITLE
Rate limit hit when connection status comes back online

### ISSUE THREAD

**Issue by trentCareApp** [GetStream/stream-chat-angular#273]
To replicate:

1. Start the sample application, dev Network Tab open
2. Turn your computer's internet source off, wait until the UI reflects this
![image](https://user-images.githubusercontent.com/77595539/167345697-a09d9379-8fd7-4fb5-88b6-31286f0852d1.png)
3. Turn internet back on

Sometimes, I get a general connection error:
![image](https://user-images.githubusercontent.com/77595539/167345992-fbff9c75-c435-4622-866e-f830cb1be0af.png)

Other times, I will get a duplicated channel list.
![image](https://user-images.githubusercontent.com/77595539/167346371-5c87f035-13e7-4c21-9de7-b636ec18350a.png)

Sometimes, I get an error in the Network tab telling me my rate limit has been hit.
![image](https://user-images.githubusercontent.com/77595539/167346568-227a63df-abb2-4fe5-ac25-6f30e7ad9715.png)

![image](https://user-images.githubusercontent.com/77595539/167348302-b08edbf8-13b8-4f12-8f01-87a27efa66d5.png)

**Comment by szuperaz** [comment]
Hi Trent,

Thanks for the bug report. I was able to identify an issue with the state recovery, this is fixed in version 3.5.1. I'll do some more testing tomorrow to ensure there aren't any other underlying issues.

Feel free to reopen this issue if the problem persists for you.
