### ISSUE TITLE
is there a way to refresh the channel list page forcefully in angular?

### ISSUE THREAD

**Issue by nkagathara** [GetStream/stream-chat-angular#336]
In angular how to refresh channel list page forcefully. and how to set channel name and logo of image also

**Comment by szuperaz** [comment]
You can call the [`reset`](https://getstream.io/chat/docs/sdk/angular/services/ChannelService/#reset) and [`init`](https://getstream.io/chat/docs/sdk/angular/services/ChannelService/#init) methods of the `ChannelService` but apart from reloading the channel list it also deselects the currently active channel, resets the message input (if a user was composing a message it gets lost) and closes the selected thread:

```typescript
this.channelService.reset();
this.channelService.init({
 // filters
});
```

What's your use case for reloading the channel list?

Here is a code snippet for creating a channel with name and image:

```typescript
async ngOnInit() {
  const channel = this.chatService.chatClient.channel('messaging', 'talking-about-angular', {
    // add as many custom fields as you'd like
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Angular_full_color_logo.svg/2048px-Angular_full_color_logo.svg.png',
    name: 'Talking about Angular',
  });
  await channel.create();
  this.channelService.init({
    // filters
  });
}
```

The code snippet is from the [Angular tutorial](https://getstream.io/chat/angular/tutorial/), more information about [creating channels](https://getstream.io/chat/docs/javascript/creating_channels/?language=javascript) can be found in our docs.

Let me know if you have any more questions.
