### ISSUE TITLE
Unable to access reactions on the first message of the channel

### ISSUE THREAD

**Issue by arnautov-anton** [GetStream/stream-chat-angular#353]
Clicking reaction icon on the first message of the channel seemingly does nothing but renders the reactions above it making them inaccesible. Not sure if design or implementation issue - probably also a problem in the React SDK.

![image](https://user-images.githubusercontent.com/43254280/180326422-e2b49381-190f-46b4-ad34-b6bf596829f4.png)

**Comment by szuperaz** [comment]
Thanks Anton, we can probably solve this from CSS for both Angular and React

**Comment by szuperaz** [comment]
Solved with adding padding to first message
