### ISSUE TITLE
Not able show the members count and online member count and streamChat text is visible in the input text box

### ISSUE THREAD

**Issue by tejastv** [GetStream/stream-chat-angular#361]
Hello,

I am using angular chat SDK in project

My Angular version is
-----------------------------------
"@angular/core": "12.2.16"

getStream Angular chat SDK
-----------------------------------
 "stream-chat": "^6.7.3",
 "stream-chat-angular": "^3.8.0",

below are the two issue i am facing 

streamChat text is visible in the input text box also the space coming before the text.

<img width="715" alt="Screenshot 2022-08-16 at 11 25 03 AM" src="https://user-images.githubusercontent.com/21055704/184809003-4f3cc6a2-8f01-42a9-8e81-f920e843cde7.png">

Not able show the members count and online member count with this tag `<stream-channel-header></stream-channel-header>`. so that i created my own component to show these count. 

but is there anything for that reason the count is not visible in given tag` <stream-channel-header></stream-channel-header>`.

<img width="1148" alt="Screenshot 2022-08-16 at 11 24 39 AM" src="https://user-images.githubusercontent.com/21055704/184809119-b60a08e5-99c4-4418-9a3b-2aa88f7d5f86.png">

Any help would be greatly appreciated!

**Comment by szuperaz** [comment]
Hi,

This happens when the translation isn't initialized in time, the 

```
this.streamI18nService.setTranslation();
```

code snippet should be called in the **constructor** of the component which contains your chat UI components (for example `AppComponent`). 

If the chat application is displayed from a lazy loaded module, you should import the `TranslateModule.forRoot()` in a non-lazy loaded module.

Let me know if this helped to solve the issue.

**Comment by tejastv** [comment]
> Hi,
> 
> This happens when the translation isn't initialized in time, the
> 
> ```
> this.streamI18nService.setTranslation();
> ```
> 
> code snippet should be called in the **constructor** of the component which contains your chat UI components (for example `AppComponent`).
> 
> If the chat application is displayed from a lazy loaded module, you should import the `TranslateModule.forRoot()` in a non-lazy loaded module.
> 
> Let me know if this helped to solve the issue.

Thanks for the reply.

Previously, I added `TranslateModule.forRoot()` in sharedModule, and sharedModule i am imported in lazy loaded module, So for that reason member and online count is not visible also the streamChat text is coming.

But after your response, shifted `TranslateModule.forRoot()` from sharedModule to appModule, 
loaded first before the lazy load module being load,

Now working perfectly fine. 

Thanks for the support.

**Comment by szuperaz** [comment]
Happy to help, don't hesitate to open a new issue if you run into any more problems.

**Comment by NaveenaM536** [comment]
> > Hi,
> > This happens when the translation isn't initialized in time, the
> > ```
> > this.streamI18nService.setTranslation();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > code snippet should be called in the **constructor** of the component which contains your chat UI components (for example `AppComponent`).
> > If the chat application is displayed from a lazy loaded module, you should import the `TranslateModule.forRoot()` in a non-lazy loaded module.
> > Let me know if this helped to solve the issue.
> 
> Thanks for the reply.
> 
> Previously, I added `TranslateModule.forRoot()` in sharedModule, and sharedModule i am imported in lazy loaded module, So for that reason member and online count is not visible also the streamChat text is coming.
> 
> But after your response, shifted `TranslateModule.forRoot()` from sharedModule to appModule, loaded first before the lazy load module being load,
> 
> Now working perfectly fine.
> 
> Thanks for the support.



> > Hi,
> > This happens when the translation isn't initialized in time, the
> > ```
> > this.streamI18nService.setTranslation();
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > code snippet should be called in the **constructor** of the component which contains your chat UI components (for example `AppComponent`).
> > If the chat application is displayed from a lazy loaded module, you should import the `TranslateModule.forRoot()` in a non-lazy loaded module.
> > Let me know if this helped to solve the issue.
> 
> Thanks for the reply.
> 
> Previously, I added `TranslateModule.forRoot()` in sharedModule, and sharedModule i am imported in lazy loaded module, So for that reason member and online count is not visible also the streamChat text is coming.
> 
> But after your response, shifted `TranslateModule.forRoot()` from sharedModule to appModule, loaded first before the lazy load module being load,
> 
> Now working perfectly fine.
> 
> Thanks for the support.

Hi,
Still issue not resolved. I am using ngx-translate plugin for multilingual and i am applied above imports in appModule and removed in sharedModule but still issue same got error like below
![image](https://user-images.githubusercontent.com/118445142/202443932-ff8c43e2-66bb-43b9-bed6-cc0014d46b4c.png)

**Comment by szuperaz** [comment]
Hi,

This is a different error, the previous one was a run time error, and this is a build time error.

Also, the errors aren't coming from `stream-chat-angular` code -> they are coming from the `voice-record.component`

But based on the error message, the problem is that the `translate` pipe isn't defined in your module. I assume that your `voice-record.component` isn't located in your `AppModule` and the containing module (probably a `SharedModule`) doesn't import the `TranslateModule` (without the `forRoot`) and therefore the `translate` pipe is not available in the `voice-record.component`.  Please refer to the ngx-translate documentation for more information: https://github.com/ngx-translate/core#sharedmodule
