### ISSUE TITLE
At the time of connect user not able to add name and image in the getstream dashboard

### ISSUE THREAD

**Issue by tejastv** [GetStream/stream-chat-angular#377]
Not able to add the name and image in the getstream dashboard At the time of connect user.

<img width="655" alt="Screenshot 2022-09-01 at 8 45 18 PM" src="https://user-images.githubusercontent.com/21055704/187950113-fa720a4e-ed88-4c8b-9203-373b7bcad478.png">

Below is the image of console log the above object to connect the user.

<img width="897" alt="Screenshot 2022-09-01 at 8 46 48 PM" src="https://user-images.githubusercontent.com/21055704/187950565-6b3fa2d3-6436-4ff2-9466-f71ab3bd1050.png">

is this the correct way to do the same.

Any help would be greatly appreciated!

**Comment by szuperaz** [comment]
Hi,

If you're using the Angular SDK you should use the [init method of `ChatClientService`](https://getstream.io/chat/docs/sdk/angular/services/ChatClientService/#init), here is an example code providing the `name` and `image` properties:

```typescript
this.chatService.init(environment.apiKey,
{
   id: environment.userId,
   name: 'Zizi',
   image: 'https://images.unsplash.com/photo-1559190394-df5a28aab5c5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80',
}, environment.userToken);
```

These changes will be immediately reflected in the chat UI:
<img width="235" alt="Screenshot 2022-09-02 at 10 27 09" src="https://user-images.githubusercontent.com/6690098/188099325-353e75ee-d643-4609-83a3-f0e209b0796f.png">

And in the dashboard as well:
<img width="1792" alt="Screenshot 2022-09-02 at 10 28 01" src="https://user-images.githubusercontent.com/6690098/188099361-49e427ed-eb6c-41ab-b3b6-6c0dba4d9b3e.png">

Let me know if this doesn't solve your problem.

**Comment by tejastv** [comment]
> Hi,
> 
> If you're using the Angular SDK you should use the [init method of `ChatClientService`](https://getstream.io/chat/docs/sdk/angular/services/ChatClientService/#init), here is an example code providing the `name` and `image` properties:
> 
> ```ts
> this.chatService.init(environment.apiKey,
> {
>    id: environment.userId,
>    name: 'Zizi',
>    image: 'https://images.unsplash.com/photo-1559190394-df5a28aab5c5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1335&q=80',
> }, environment.userToken);
> ```
> 
> These changes will be immediately reflected in the chat UI: <img alt="Screenshot 2022-09-02 at 10 27 09" width="235" src="https://user-images.githubusercontent.com/6690098/188099325-353e75ee-d643-4609-83a3-f0e209b0796f.png">
> 
> And in the dashboard as well: <img alt="Screenshot 2022-09-02 at 10 28 01" width="1792" src="https://user-images.githubusercontent.com/6690098/188099361-49e427ed-eb6c-41ab-b3b6-6c0dba4d9b3e.png">
> 
> Let me know if this doesn't solve your problem.

Ohk, Fixed now, i dont know i am using javascript method, but after using angular SDK working fine.

Thanks.
