### ISSUE TITLE
In one to one chat opposite user image is not visible

### ISSUE THREAD

**Issue by tejastv** [GetStream/stream-chat-angular#380]
In Angular SDK at the time of one to one chat opposite user image is not showing automatically in the header. 
In Android SDK at the time of one to one chat SDK is taking image of opposite user image or name automatically. 

Example:

I am the A user and wants to chat with B. so for one to one chat need to create channel. 
so at the time of channel create need to set B user image as a channel image.

then B from android app try to chat with A in the same channel B can see his own image in the header rather than the A image.

Because in Android SDK if the connected user wamts to chant with opposite user in the same channel it will take opposite user image or name automattically and display in header that is not heppening in Angular SDK.

Please let me know if not understood.

Any help that whould me appriciated.

Thanks.

**Comment by szuperaz** [comment]
Hi,

You're right, the Angular SDK doesn't display the other user's avatar image in case of 1:1 channels, even though it makes sense (especially if Andriod does so). I've added this feature, it should be released soon. This issue will be updated once the release is done, so you'll be notified.

Let me know if something else comes up.
