### ISSUE TITLE
Send Message on click of a custom button

### ISSUE THREAD

**Issue by tejastv** [GetStream/stream-chat-angular#382]
I am not able to find the corract syntax for send message with attechment if any on click of a custom button in angular SDK documentation. Angular SDK documentation is not clearly understandable.

<img width="1173" alt="Screenshot 2022-09-16 at 10 13 27 AM" src="https://user-images.githubusercontent.com/21055704/190558358-3adba469-19d4-4266-9a61-221873287e60.png">

Can anyone share the proper syntax for the same.

Also In case of using custom button to send message, at that time if i atteched any file that time showing me the send button, so in image i have two send button, so how to fix this.

<img width="1166" alt="Screenshot 2022-09-16 at 10 17 47 AM" src="https://user-images.githubusercontent.com/21055704/190558758-4f24ed75-6a65-4311-9818-161af1acaa65.png">

Any help that whould be appriciated.

**Comment by szuperaz** [comment]
I've created an example for reading the attachments uploaded to a message input, I assume you have a similar setup in your project https://github.com/GetStream/stream-chat-angular/commit/841656cf64d9aff972743ae8d0c641c3079cd681

**Comment by tejastv** [comment]
> I've created an example for reading the attachments uploaded to a message input, I assume you have a similar setup in your project [841656c](https://github.com/GetStream/stream-chat-angular/commit/841656cf64d9aff972743ae8d0c641c3079cd681)

Yes, Documatation is not well documented, it's just a simple text, no code snippet and all,

Below attenched screenshot to access the text from templete and send to current channel, 
Is this the correct way to access? OR 
Once i send the message in channel need clear attechments and message from input so how i do it?

<img width="761" alt="Screenshot 2022-09-19 at 3 08 00 PM" src="https://user-images.githubusercontent.com/21055704/190990259-590eb8cb-80ac-462c-a528-7aa055e4a01d.png">

<img width="714" alt="Screenshot 2022-09-19 at 3 07 33 PM" src="https://user-images.githubusercontent.com/21055704/190990212-c46e3d5a-94a3-4ea2-a75a-8b54ab3149ae.png">

**Comment by szuperaz** [comment]
It seems that you're trying to emulate the message input's [`messageSent` method](https://github.com/GetStream/stream-chat-angular/blob/master/projects/stream-chat-angular/src/lib/message-input/message-input.component.ts#L293)

Among other tasks, it does indeed [resets attachments after the message sent](https://github.com/GetStream/stream-chat-angular/blob/master/projects/stream-chat-angular/src/lib/message-input/message-input.component.ts#L347).

By the way, have you tried just using the default submit handler inside the message input component? I think that should be simplest solution provided you don't want to change the implememntation https://github.com/GetStream/stream-chat-angular/commit/78e1e8587e3ef0025cdeb75662af3e019e45e03a

**Comment by tejastv** [comment]
> It seems that you're trying to emulate the message input's [`messageSent` method](https://github.com/GetStream/stream-chat-angular/blob/master/projects/stream-chat-angular/src/lib/message-input/message-input.component.ts#L293)
> 
> Among other tasks, it does indeed [resets attachments after the message sent](https://github.com/GetStream/stream-chat-angular/blob/master/projects/stream-chat-angular/src/lib/message-input/message-input.component.ts#L347).
> 
> By the way, have you tried just using the default submit handler inside the message input component? I think that should be simplest solution provided you don't want to change the implememntation [78e1e85](https://github.com/GetStream/stream-chat-angular/commit/78e1e8587e3ef0025cdeb75662af3e019e45e03a)

This is the best solution, using one line i can able to send the message and attechments, 
You see the documatation is not that good to understand, it just the simple text and very less reference to the specific methods or topics.

If you guys can made the doc well so that whould be great.

Thanks for the quick respons.
