### ISSUE TITLE
Issue: Even After removing the members from the channel still can able to send the message to that person.

### ISSUE THREAD

**Issue by tejastv** [GetStream/stream-chat-angular#383]
In Angular SDK facing. issue 

I can able to send the message Even After removing the member from the channel still can able to send the message to that person.

**Step 1:** Create common channel from three four user.
**Step 2:** Open same Channel in two window. with two seperate user login.
**Step 3:** Remove member from first window. (You can see on the second window specific channel is not visible)
**Step 4:** Send message on the same channel on first window. (You can able to see that channel again appears in the second window, Even it's not visible in the getstream dashboard into that channel members list, and in messages tab message is generated with combination of two ids same like normal flow)

Please let me know, if not understood.

Any help that whould be appriciated.

**Comment by szuperaz** [comment]
Hi,

Thanks for the report, I was able to reproduce the issue, and a fix is on the way.

This issue will be updated once the release is done.

**Comment by tejastv** [comment]
> Hi,
> 
> Thanks for the report, I was able to reproduce the issue, and a fix is on the way.
> 
> This issue will be updated once the release is done.

Thanks.
