### ISSUE TITLE
Angular 16 Compatibility

### ISSUE THREAD

**Issue by Sukanya-techie96** [GetStream/stream-chat-angular#419]
Hello 
Is there any updated command or releasing a new version supportive to Angular 16 ?

**Comment by szuperaz** [comment]
Hi,

Not yet, currently, Angular 15 is the latest version that we support, but we are keeping an eye out for the stable Angular 16 release, and we are planning to add support shortly after that. I'll update this ticket once it's all done.

**Comment by szuperaz** [comment]
Hi,

Angular 16 is now supported:
- Installation: https://github.com/GetStream/stream-chat-angular#installation
- Tutorial: https://getstream.io/chat/angular/tutorial/
