### ISSUE TITLE
Channel related queries

### ISSUE THREAD

**Issue by Sukanya-techie96** [GetStream/stream-chat-angular#428]
1. How to trigger channel actions (delete, mute) from a custom three-dots button on header of channel preview as there's no way to pass channel details as function argument?
2. How to hide member counts from channel preview header of one-to-one chat?
3. After channel creation, how to trigger notification for unread messages & it's count?

**Comment by szuperaz** [comment]
1. We have a [guide on how to add actions to the channel header](https://getstream.io/chat/docs/sdk/angular/components/ChannelHeaderComponent/#channel-actions) - let me know if that doesn't answer some of your questions
2. [You can provide your own template to override the member count UI](https://getstream.io/chat/docs/sdk/angular/services/CustomTemplatesService/#channelheaderinfotemplate)
3. When a new channel is created that the logged-in user is a member of the new channel will be automatically added to the top of the channel list and the channel preview will show the number of unread messages. This mechanism is done by using the [`notification.added_to_channel` event](https://getstream.io/chat/docs/sdk/angular/services/ChannelService/#channels)

**Comment by Sukanya-techie96** [comment]
1. I tried with custom message action box with boxicon icons, the icons are not displayed and the action texts are shown as "streamChat.pin" even though the translation mosule is imported in the app.module.ts file.
2. Where can we show all the pinned messages?

**Comment by szuperaz** [comment]
1. I wasn't able to reproduce your issues, but I did find a problem with custom message action items, please update to stream-chat-angular@4.26.1 and follow the updated example: [custom component](https://github.com/GetStream/stream-chat-angular/tree/master/projects/customizations-example/src/app/message-action) | [usage](https://github.com/GetStream/stream-chat-angular/blob/bfb4e23c879abbb2d857d4cfd7af11bfe09061ac/projects/customizations-example/src/app/app.component.html#L172-L187). Let me know if your problems are still present, and please send me your custom template and the code that shows how do you use the custom template.
2. We have a [guide on pinned messages](https://getstream.io/chat/docs/sdk/angular/code-examples/pin-messages/) that retrieves the last 10 pinned messages and then appends newly pinned messages to the list. If you want to show all pinned messages [you can retrieve the paginated list of pinned messages](https://getstream.io/chat/docs/javascript/pinned_messages/#retrieve-pinned-messages).

**Comment by Sukanya-techie96** [comment]
1. Followed the custom message action Item template and got below error translate pipe.
![image](https://github.com/GetStream/stream-chat-angular/assets/86222357/03875f46-e8bd-48ec-837e-2dcb50f9c410)

**Comment by szuperaz** [comment]
This error happens if the `TranslateModule` isn't available in the module where the `message-actions-component` is located. If you imported the `TranslateModule` in your `AppModule` and the `message-action-component` is in the `chatting` module then you might be missing an import in the `chatting` module:

```
imports: [TranslateModule]
```

For more information see: https://github.com/ngx-translate/core#usage

**Comment by Sukanya-techie96** [comment]
Could you please guide me to create a Thread Reply like section to show Channel details?

**Comment by szuperaz** [comment]
You can provide a template to show a custom thread header: [docs](https://getstream.io/chat/docs/sdk/angular/services/CustomTemplatesService/#threadheadertemplate), [example](https://github.com/GetStream/stream-chat-angular/blob/master/projects/customizations-example/src/app/app.component.html#L229-L238)

**Comment by Sukanya-techie96** [comment]
Is there any specific keys available in channel to identify whether it's a group chat or one-to-one chat?

**Comment by szuperaz** [comment]
Unless you create the channels with different [types](https://getstream.io/chat/docs/javascript/channel_features/?language=javascript) there is no flag, you have to check the members array and determine this information based on that;

**Comment by Sukanya-techie96** [comment]
Could you please guide me for pagination work on Users list & channels list ?
Do i need to do it with customizations-example OR it's inbuilt in stream-chat-angular with some minor modifications?

**Comment by szuperaz** [comment]
- The channel list is paginated by default: https://getstream.io/chat/docs/sdk/angular/services/ChannelService/#init
- We don't have a user list component, but we have an API for querying members: https://getstream.io/chat/docs/javascript/query_members/?language=javascript

**Comment by Sukanya-techie96** [comment]
1. On page load getting fixed 30 users sorted with last created every time and all the channels at once.
2. In the request payload tried with offset value less than 30 (fixed number of users) but got same 30 users.

**Comment by szuperaz** [comment]
1. You can use the [`member_limit`](https://getstream.io/chat/docs/javascript/query_channels/?language=javascript#query-options) option in the `ChannelService.init` method specify the number of members to fetch
2. You can use the [`limit`](https://getstream.io/chat/docs/javascript/query_members/?language=javascript#query-options) option of the `queryMembers` to specify the number of members to be fetched. The `offset` option is there to control pagination, to specify which page to fetch.

**Comment by Sukanya-techie96** [comment]
When trying to add members in Group Chat below error is appearing. Let me know what can be wrong with the authorization? I've checked the API error codes as well, not able to recognize what's wrong with the addMembers() method.
```
StatusCode: 403
code:17
message: "UpdateChannel failed with error: \"cannot add members to the distinct channel they don't belong to, please create a new distinct channel with the desired members\""
```

**Comment by szuperaz** [comment]
Already answered here: https://github.com/GetStream/stream-chat-angular/issues/432
