### ISSUE TITLE
channel create bifurcation issue

### ISSUE THREAD

**Issue by Sukanya-techie96** [GetStream/stream-chat-angular#432]
When trying to add members in Group Chat below error is appearing. Let me know what can be wrong with the authorization? I've checked the API error codes as well, not able to recognize what's wrong with the addMembers() method.
```
StatusCode: 403
code:17
message: "UpdateChannel failed with error: \"cannot add members to the distinct channel they don't belong to, please create a new distinct channel with the desired members\""
```

**Comment by szuperaz** [comment]
This can happen if you create a channel without an ID, with a set list of members: see docs: https://getstream.io/chat/docs/javascript/creating_channels/?language=javascript#2.-creating-a-channel-for-a-list-of-members
