### ISSUE TITLE
Channel updates delete message drafts

### ISSUE THREAD

**Issue by nvahalik** [GetStream/stream-chat-angular#440]
To reproduce:

1. Set up the sample app.
2. Login as a user (any user).
3. Open a chat and start writing a message.
4. In the Chat Explorer (GetStream dashboard), find the channel you opened in step 3.
5. Rename the channel.

Your draft message will have disappeared.

As a workaround, we have rewritten this section here:

https://github.com/GetStream/stream-chat-angular/blob/master/projects/stream-chat-angular/src/lib/message-input/message-input.component.ts#L155-L166

**Comment by szuperaz** [comment]
Thanks for reporting this bug. It's now fixed and will be released shortly. Feel free to reopen the ticket if it doesn't work as expected.
