### ISSUE TITLE
Message actions not properly visible

### ISSUE THREAD

**Issue by szuperaz** [GetStream/stream-chat-angular#453]
This is caused by an underlying issue in a lib that we use: https://github.com/tonysamperi/ngx-popperjs/issues/52

This also affects
- hover info for reactions
- hover info for message status

**Comment by szuperaz** [comment]
Quick fix is available in stream-chat-angular@4.32.1

**Comment by askomsoey** [comment]
Hi Zita, thank you for the quick fix, we were running into a lot of this issue as well 👍 But unfortunately after upgrading from 4.28.0 to 4.32.1 we started having other issues and bugs connected to templates, that we didn't have before. A ton of "RangeError: Maximum call stack size exceeded" errors

![image](https://github.com/GetStream/stream-chat-angular/assets/98821734/097580e3-8ef5-4c70-8022-670b47e8a5c0)
![image](https://github.com/GetStream/stream-chat-angular/assets/98821734/6e7c263e-dd5b-4090-a24e-bb7b970d1d57)
![image](https://github.com/GetStream/stream-chat-angular/assets/98821734/72dc5670-704f-4763-ac8e-3a3b5e765526)


Has this been reported already? If so, do you know what could be the issue? Thanks!

**Comment by szuperaz** [comment]
Hi,

It hasn't been reported before, I've tested with our [customizations example app](https://github.com/GetStream/stream-chat-angular/tree/master/projects/customizations-example) that has a lot of ng templates, but I couldn't reproduce the bug.

Please try if version 4.30.0 works for you. Because it might be those changes that could cause the problems. Are these errors present for all of your custom templates or just some? If for just some, can you please specify which ones?

**Comment by szuperaz** [comment]
I've created a test app with custom attachments and message actions on this branch: https://github.com/GetStream/stream-chat-angular/tree/call-stack-reproduction, and ran it in Google Chrome inside an Android emulator (see attached video) but  unfortunately, I was unable to reproduce it.

Please try and reproduce the problem in the linked sample app ([how to run](https://github.com/GetStream/stream-chat-angular/tree/call-stack-reproduction#sample-app)).

https://github.com/GetStream/stream-chat-angular/assets/6690098/bb90121b-657d-4a00-bb73-0d0aa7836f0c

**Comment by askomsoey** [comment]
I went over and confirmed on our app the change happened from [4.29.1-4.30.0](https://github.com/GetStream/stream-chat-angular/compare/v4.29.1...v4.30.0), however I'm not sure if it's due to a special implementation on our side, I just downloaded the demo you made, but I don't have a user to test, without involving server side to get a user, do you have any test users with messages that could be used instead? Thanks

**Comment by askomsoey** [comment]
Here is also an example of where it happened to a very simple change, but somehow with the changes in 4.30.0, it is broken, note the emulator renderer, not sure if it is helpful
![image](https://github.com/GetStream/stream-chat-angular/assets/98821734/8671eb96-fbd9-4178-b36d-2fe9db5d7612)
![image](https://github.com/GetStream/stream-chat-angular/assets/98821734/55f959f5-38f7-4f0a-9fcd-dfdea104421a)

**Comment by szuperaz** [comment]
I've updated the reproduction app 
- To use one of our demo app to authenticate
- Added a custom avatar template as well

**Comment by askomsoey** [comment]
On the callstack issues, one of our devs found a workaround a while back, might have been patched in a new version of the SDK. 

On the note of the issues with the Message Actions, I was wondering if this issue includes the actions menu being cut off?
![image](https://github.com/GetStream/stream-chat-angular/assets/98821734/86013df3-c781-43c7-841e-325d904d3b6c)

**Comment by szuperaz** [comment]
I think this was a side effect of the quick fix, stream-chat-angular@4.36.0 contains the official fix for the library that we use for the menu position, let me know if you still experience this problem with stream-chat-angular@4.36.0

**Comment by askomsoey** [comment]
@szuperaz Thank you for letting me know, the issue where it gets cut off seems to have been fixed from what I can see, I'm sending it to the testers to confirm 👍 But can be considered solved for now from my side at least. Thank you again!

**Comment by szuperaz** [comment]
Thanks for the quick reply, I'll close the issue, but feel free to reopen it if the problem returns.
