### ISSUE TITLE
Styles broken when using Angular tutorial

### ISSUE THREAD

**Issue by OP-Klaus** [GetStream/stream-chat-angular#457]
Following the Angular tutorial from https://getstream.io/chat/angular/tutorial/ results in a page that looks like this:

<img width="1173" alt="image" src="https://github.com/GetStream/stream-chat-angular/assets/12147748/6d64d50d-0392-49e7-afe9-a034c186af23">

I have reproduced it, and had a colleague independently reproduce on another machine. We have tried with Angular 16 and 14.

There are no console errors and no failed network requests.

**Comment by szuperaz** [comment]
Does it solved by reloading the page, or does it always look like this?

**Comment by OP-Klaus** [comment]
@szuperaz it always looks like this

**Comment by OP-Klaus** [comment]
@szuperaz thank you for providing these repositories, that let me diff the repositories and see what I did wrong.

I was adding the styles to `app.component.scss` instead of `styles.scss`. This was 100% my mistake, but it might be a good idea to add a note to the tutorial in case other people do the same thing.

I have another problem, if I copy new credentials again from the Angular tutorial page, I get the following error on load:
```
{
    "code": 17,
    "message": "GetOrCreateChannel failed with error: \"User 'nameless-brook-1' with role 'user' is not allowed to perform action ReadChannel in scope 'messaging'\"",
    "StatusCode": 403,
    "duration": "0.00ms",
    "more_info": "https://getstream.io/chat/docs/api_errors_response",
    "details": []
}
```

but my previous user `steep-dawn-1` still works, which also came from the Angular tutorial.

**Comment by szuperaz** [comment]
For tutorials, there is a demo Stream application with API key `dz5f4d5kzrue`, that has special permission settings. If you're logged in to your Stream dashboard you might see a different API key in the tutorial.

The default permissions only allow users to read channels they are a member of, so you'll have to create a new channel, and add your user as a member (you can do this on your Stream dashboard) and [filter for channels the user is a member of](https://getstream.io/chat/docs/javascript/query_channels/?language=javascript#messaging-and-team).

The other solution is to open the tutorial in a private browser tab, and copy the credentials from there, which will use the demo application.

**Comment by OP-Klaus** [comment]
@szuperaz thank you for explaining, I'm very happy with the support here
