### ISSUE TITLE
Broken styles when inside existing app

### ISSUE THREAD

**Issue by OP-Klaus** [GetStream/stream-chat-angular#461]
I have copied the example code into my existing app and it is functioning correctly, except for the styles.

I can see in the example app that it is matching the selector `.str-chat__message-input .str-chat__send-button`:
<img width="692" alt="image" src="https://github.com/GetStream/stream-chat-angular/assets/12147748/d360a2c1-f30d-4199-9928-959a2ca47a36">

but in my app, that selector does not exist, instead I have `str-chat__input-flat`:
<img width="624" alt="image" src="https://github.com/GetStream/stream-chat-angular/assets/12147748/585b9616-c048-4345-ad05-b5b4a796f31e">

which causes it to miss the styling:
<img width="299" alt="image" src="https://github.com/GetStream/stream-chat-angular/assets/12147748/ca1ba6d8-f790-4c1d-a5a3-94fd1070af82">

Looking at the contents of `node_modules/stream-chat-angular/src/assets/styles/v2/css/index.css` there is no mention of `str-chat__input-flat`.

I am probably missing something obvious, please help

**Comment by szuperaz** [comment]
If you're using theme v2 there is no `str-chat__input-flat` class, in your app the `stream-message-input` component thinks it's being used in theme v1. This shouldn't happen if the theme v2 stylesheet is imported correctly. 

If you inspect the `stream-message-input` element in your browser developer tools, do you see the `--str-chat__theme-version` variable being set to `2`?

<img width="317" alt="Screenshot 2023-08-22 at 11 43 09" src="https://github.com/GetStream/stream-chat-angular/assets/6690098/29d7b680-f1f1-4f80-85b7-1730d6eb1c0c">

**Comment by OP-Klaus** [comment]
@szuperaz thanks for your reply. My CSS preprocessor was stripping out some of the CSS and I have fixed that now
