### ISSUE TITLE
[Avatar] Empty place holder still render image

### ISSUE THREAD

**Issue by weiz18** [GetStream/stream-chat-angular#464]
Hey, 

Inside message list, i can see that an avatar placeholder still has image attached which generating duplicate calls to fetch the same image or invisible image. is there anyway to cache or to use empty div instead of image for placeholder to improve performance ? 

thanks ! 
 
<img width="319" alt="image" src="https://github.com/GetStream/stream-chat-angular/assets/42139732/fe8ca987-702a-4f28-9d53-51eda7e4b670">

**Comment by szuperaz** [comment]
Hi,

I don't see multiple requests in the network monitor of the sample application, but we rely on the cache mechanism of the browser, It's possible that your requests can't be cached by the browser. Nevertheless, I can imagine that other integrators could have a similar setup, I'll look into this and get back to you once I have a fix for this.
