### ISSUE TITLE
Enable user reaction list tooltip/popup

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#494]
I need to see a list of users who reacted with emoji and I noticed that it's turned off in css.

<img width="303" alt="image" src="https://github.com/GetStream/stream-chat-angular/assets/25200186/5361f983-1295-4c90-a2cc-5429aaa71a44">

**1. What are these themes v1 and v2, and how do I select a theme?**

I can overwrite some CSS to make it kinda work but it would only result in one line with all of the names:

![image](https://github.com/GetStream/stream-chat-angular/assets/25200186/40ba07b2-cb40-4eb6-a79a-82022c08aa81)

**2. Do you plan to make it more powerful like in Flutter where you can see avatars and stuff?** 

<img width="627" alt="image" src="https://github.com/GetStream/stream-chat-angular/assets/25200186/e32c032e-19d9-446f-b562-92f1667568fd">

Btw, I'm using custom components for everything and I can implement a custom detailed list myself, but I wouldn't do it if it was in your plans already.

**Comment by szuperaz** [comment]
**1. Theme**

You can choose between theme v1 and v2 by importing the corresponding stylesheet. To use theme v2 you can follow [this guide](https://getstream.io/chat/docs/sdk/angular/theming/themingv2/). If `v2` doesn't appear in your stylesheet import, you're using v1.

For theme v1 the tooltip is displayed once you open the reactions selector with the ":)" button, screenshot:
![Screenshot 2023-10-25 at 14 28 33](https://github.com/GetStream/stream-chat-angular/assets/6690098/48095926-db10-4373-ba0c-0247252ba6a6)

For theme v2 the tooltip is displayed once you hover over an existing reaction:
![Screenshot 2023-10-25 at 14 27 39](https://github.com/GetStream/stream-chat-angular/assets/6690098/60c896aa-a2fc-4600-865f-8b788cbe1f80)

**2. Reaction details**

It's in our backlog, but it's not planned for the foreseeable future, so it's best to go with a custom implementation.

Feel free to reopen the ticket if you have further questions about the topic.
