### ISSUE TITLE
keepAliveChannels$OnError should be `true` by default

### ISSUE THREAD

**Issue by nvahalik** [GetStream/stream-chat-angular#500]
If you happen to have a timeout while doing `queryChannels()`, by default it will call `error()` on the `channelsSubject`:

https://github.com/GetStream/stream-chat-angular/blob/172a38325ad2fe58d6c14e4835900df0f2fdabd9/projects/stream-chat-angular/src/lib/channel.service.ts#L1508C2-L1510

The problem here is that this **kills** the client the first time an error occurs. Even if subsequent calls work, you've already called `error()` on your `BehaviorSubject()`. It's closed and **every time you try to subscribe to the channel subject, it'll throw the error again and again and again.**

So, please:

1. Make `keepAliveChannels$OnError: true` by default.
2. Add this to the docs.

**Comment by szuperaz** [comment]
Thank you for your feedback.

1. Making `keepAliveChannels$OnError: true` by default is a breaking change, so it will only be done in the SDK's next major release
2. The [docs](https://getstream.io/chat/docs/sdk/angular/services/ChannelService/#channels) has been updated to contain information about `keepAliveChannels$OnError`.

**Comment by nvahalik** [comment]
@szuperaz You say this is a breaking change, but this is a **MAJOR BUG**.

If you *ever* receive an error during any operation, you've effectively KILLED your client and no recovery is available.

Even if you call `reset()`, that `BehaviorSubject` is _completely_ dead and will just return an error any time you try to do anything with it. I _highly_ doubt this is the way you intend it to function.

We just found another scenario in which this can kill an application: We have a special channel which is managed a bit differently than the other channels. If the user happens to query this channel before `ChannelService.init()` is called, and an error is returned, then we've entered into a state where the app is completely broken and only a full reload (or in the case of a mobile app, we'd have to kill and reload the app).

Now, yes, we can work around this, but again, this is a BUG which _must_ be worked around in order for it to work properly.

**Comment by szuperaz** [comment]
The reason this is treated as a breaking change is that the default behavior is working fine in the sense that the SDK won’t be in an inconsistent state if an error occurs. The default UI components handle the case when the stream emits an error.

I agree that having to reload the whole page/mobile app is bad UX. That’s why we’re changing this behavior in the next major release.

It’s also not ideal that you need to opt-in for the logical behavior. However, if we were to change it in a non-breaking release, we would break existing integrations in a very hard-to-detect way.

I also see how not knowing the SDK’s error-handling works can lead to unexpected bugs in your application. That’s why we updated our docs immediately to write about the two different error-handling mechanisms once you raised this issue.
