### ISSUE TITLE
Deleting channel causes an error

### ISSUE THREAD

**Issue by elongberg** [GetStream/stream-chat-angular#501]
Calling `channel.delete()` on an active channel successfully deletes the channel, but causes an error `You can't use a channel after client.disconnect() was called`.
![image](https://github.com/GetStream/stream-chat-angular/assets/14004275/124731c6-d82f-4e2b-95b7-8bf2d0124f75)

It looks like `ChannelService.handleChannelDeleted` is calling `removeChannelsFromChannelList`, which calls `stopWatching` on the channel and results in the error.

**Comment by szuperaz** [comment]
Thank you for reporting this bug. A fix is on the way and will be released shortly. Feel free to reopen the ticket if something doesn't work as expected.
