### ISSUE TITLE
Open link attachments in new tab

### ISSUE THREAD

**Issue by elongberg** [GetStream/stream-chat-angular#550]
Right now, clicking a link in a message opens that link in the same window.
This is a request to change it to opening in a new tab, like the (react-based) example does [https://getstream.io/chat/demos/messaging/](https://getstream.io/chat/demos/messaging/)

**Comment by szuperaz** [comment]
This makes sense. I can't give you an exact ETA, but we will try to add this in the coming weeks. You'll be notified via this issue when this is released.

**Comment by frozenfrank** [comment]
@szuperaz I just submitted a PR that addresses this issue, but it's my first time contributing to this repo. I filled out the contributors form and modified the tests properly. Is there anything else I can do to help see this issue through?
