### ISSUE TITLE
Allow controlling avatar sizes through CSS variables

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#569]
Right now there doesn't seem to be a way to change avatar sizes in a nice way: you should either use dirty CSS overwrites or create custom components for the components-hosts of `<stream-avatar-placeholder>`, which would allow you to pass the size directly.

What's the idea behind having sizes set through JS and not CSS?
Can you add a way to control the sizes through CSS variables?

**Comment by szuperaz** [comment]
I agree that it makes more sense to have CSS variables to control avatar size. I'll try to squeeze this in the coming weeks, in the meantime, the dirty CSS overwrites are the way to go.

**Comment by ilyakonrad** [comment]
Thanks!
