### ISSUE TITLE
Global idea for customization

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#572]
Recently I started refactoring our chat by going back from complete custom components to your standard components. 
I already opened three tickets about what I would like to have at my disposal in different components and it's got me thinking if there's a more powerful way to do customization.

I've spent some time imagining an ideal use of your components if I want to customize some things and this is what I came up with.
I don't need to customize business logic, data or behavior. It's what the library is supposed to cover and it does. However I do sometimes need to change or add some things. Change the order of some elements in the html or add things that are available through the API but not present in the layout.

Let's take [Angular Material's table component](https://material.angular.io/components/table/examples) as an example. You can put anything in the cell (header cell or body cell), in any order, and you still have access to the data of respective row. You can customize header cell however you want and still have the default click listeners that trigger sorting and the default sorting icon. It's really useful and allowed us to even create a custom wrapper component for tables.

![image](https://github.com/GetStream/stream-chat-angular/assets/25200186/0b50a7c6-44d7-48f3-841c-585fa3faa834)

This is how I see the perfect way to use the default stream chat components while customizing some elements inside of them.
Let's say I want to customize avatars in ChannelPreview component in channel list and maybe show some additional data:
```
<stream-channel-list>
  <!-- List any components on any level used inside of stream-channel-list that you want to customize -->
  <stream-channel-preview *customChannelPreviewIdentifier="let channel">
    <stream-avatar *customAvatarComponentIdentifier>
      <img *customAvatarImgIdentifier [src]="channel.latest_message.author.avatar.src" />

      <div *customAvatarLetterIdentifier class="custom-letter-class-name">
        {{ channel.latest_message.author.name.slice(0, 1) }}

        <!-- Add new elements -->
        <span class="some-custom-decorative-thing"></span>
      </div>
    </stream-avatar>

    <div class="custom-preview-text-wrapper">
      <!-- Change order of the elements -->
      <p>{{ channel.latest_message.text }}</p>
      <p>{{ channel.latest_message.author.name }}</p>

      <!-- Add available data that's not displayed by default -->
      <p>{{ channel.latest_message.date | date }}</p>
    </div>
  </stream-channel-preview>
</stream-channel-list>
```

Let me know how far it is from reality 😄

**Comment by szuperaz** [comment]
I think we use the same high-level logic as Angular Material does. There are customization points in the SDK components where you can inject custom templates, and the SDK will provide you with the necessary context that contains the data your UI needs. So, I don't think there is an inherent architectural difference (however, the Angular Material syntax is more elegant).

Based on your example, you'd like to have finer control over the UI. For example, the SDK allows you to override the whole [avatar](https://getstream.io/chat/docs/sdk/angular/components/AvatarComponent/#customization) component but not the image or the initials parts separately. Another example was the [channel preview](https://github.com/GetStream/stream-chat-angular/issues/570#issuecomment-2025597345), where you wanted to display some extra data, but the existing customization options made this hard, so we've added a new customization point. These all make sense. We'd like to encourage anyone who runs into a customization limitation with the SDK to open a GH request, and we'll evaluate it based on available resources/priorities.
