### ISSUE TITLE
Remove online indicator from group chat avatar

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#576]
I think it doesn't make sense to show the online indicator in a group chat at all.
But if you don't agree, I would suggest to at least hide it if you're the only one online.

<img width="597" alt="image" src="https://github.com/GetStream/stream-chat-angular/assets/25200186/5e4e6d9a-8e2d-4ab0-85f7-fe7de4f7face">

**Comment by ilyakonrad** [comment]
As far as I see, the indicator indeed wasn't supposed to be there, I noticed that it doesn't appear immediately, but after you open any one-on-one chat where that person is online and then come back. The indicator component doesn't seem to update correctly.

**Comment by szuperaz** [comment]
Yes, it's a bug. Thanks for reporting it. It'll be fixed soon.
