### ISSUE TITLE
Can't spin up the project for local development

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#591]
I ran `npm i`, created `.env` file, now I'm getting this when running `npm start`:

`'ANGULAR_ENV' is not recognized as an internal or external command, operable program or batch file.`

![image](https://github.com/GetStream/stream-chat-angular/assets/25200186/9205ed2f-eac2-4a8b-ab05-66e852802ba3)

**Comment by szuperaz** [comment]
This could be the line that sends the error: https://github.com/GetStream/stream-chat-angular/blob/master/package.json#L27. Are you on Windows? Environment variables are set differently there. Unfortunately we don't usually test the SDK set up on Windows, so it's possible we have issues there.

**Comment by ilyakonrad** [comment]
Yep, I am. Could you orient me on how to overcome this?

**Comment by szuperaz** [comment]
Unfortunately, I won't be able to test all this in Windows right now to fix the errors, we had a similar issue before: https://github.com/GetStream/stream-chat-angular/issues/521 - I'll close this in favor of the existing issue.

You can either decide not to contribute, or if you want to contribute, you'd need to change the OS-dependent parts of the related scripts.
