### ISSUE TITLE
stream-channel shows messages from previously selected channel while loading the relevant ones

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#601]
Recently we got feedback from a few users complaining about seeing wrong messages. Specifically those were messages from a previously viewed chat.

I was able to reproduce it by playing around with network speed in Chrome DevTools and noticed that if you (the stream-chat API) can't load messages in under 3 seconds, it'll cancel the API call with an error from Axios "timeout of 3000ms exceeded".

That leaves users with irrelevant messages in the channel worrying about privacy 🤷‍♂️ 

The "Slow 3G" preset in Chrome barely cuts it, taking 2 seconds to load. Here's the Network config that will help to reproduce it.
![image](https://github.com/GetStream/stream-chat-angular/assets/25200186/ce632662-b31a-4541-9782-a4bd7954502c)

Reproduction:
1. Open a channel, write a few messages.
2. Slow down the network speed (possibly with custom network config).
3. Switch to another channel.

Issues:
1. Regardless of the timeout situation, I see that stream chat doesn't clear messages from previously selected channel _while_ loading the new channel and I think it's not right, it looks like the system is unresponsive/unstable in a way. I would expect to see empty channel when loading messages.

2. As for the timeout itself, I don't get the point of having it in the first place. But at least in case it takes too long to get messages or the connection fails, I would expect messages to try to load again as soon as the network is restored. In any case, 3 seconds seems like an extremely small timeout.

**Comment by ilyakonrad** [comment]
Sorry, I meant changing channels programmatically, not via channel list. We have a UserProfile component, where we have

```
<stream-channel>
  <stream-message-list></stream-message-list>
  <stream-message-input></stream-message-input>
</stream-channel>
```
to be able to contact the person directly. So this is what I call when switching channels:

```
private setChatChannel(): void {
  const channel = this.chatClientService.chatClient.channel('messaging', {
    members: [this.currentUser.uuid, this.user!.profile_picture!.uuid!]
  })

  this.channelService.channels$
    .pipe(
      // This will get us the current channel list (if list is not yet inited, it will wait for init)
      filter((channels) => !!channels),
      take(1)
    )
    .subscribe(async () => {
      try {
        await channel.watch()
      } catch (error) {
        this.snackbarService.error(error.message)
        throw error
      }
      this.channelService.setAsActiveChannel(channel)
    })
}
```

**Comment by szuperaz** [comment]
I think I see the problem: you should move the `setAsActiveChannel` inside the try-catch block. You should only call `setAsActiveChannel` with an initialized channel, otherwise the method can run into an error, and that can lead to a compromised state between `activeChannel$` and `activeChannelMessages$`, IF you had a previous active channel set.

I made a note to myself to add better error handling in the SDK to avoid inconsistent state, also, the docs could be more clear about this.

Let me know if this doesn't solve your issue.

**Comment by ilyakonrad** [comment]
Moving `.setAsActiveChannel()` after `await channel.watch()` didn't help.
Moving it _before_ `await channel.watch()` kind of helped to not show the previous chat, but throws error if the channel I open doesn't have messages, which breaks the chat completely.
![image](https://github.com/GetStream/stream-chat-angular/assets/25200186/6f675d58-6996-4142-b896-377813887c27)
![image](https://github.com/GetStream/stream-chat-angular/assets/25200186/f3ff20d0-6087-44d2-b098-bb81991c31e8)

**Comment by szuperaz** [comment]
Can you please tell how it didn't help? If `watch` fails it will throw an error, which will prevent `setAsActiveChannel` from executing. This shouldn't lead to compromised state.

This should be the code:

```
try {
  await channel.watch();
  this.channelService.setAsActiveChannel(channel)
} catch (error) {
    this.snackbarService.error(error.message)
    throw error
}
```

**Comment by ilyakonrad** [comment]
It doesn't seem to change the behavior, I still get a glimpse of previous channel messages when opening another channel. Do you need more context about our setup?

**Comment by szuperaz** [comment]
"I still get a glimpse of previous channel messages when opening another channel" -> my guess if that your UserProfile chat component hooks on to `activeChannel$`. If you want to make sure that your UserProfile chat component shows only a specific channel or nothing you need to deselect the previous active channel before opening the chat in your UserProfile component. If the user can open the UserProfile component while `channelService.init` is in progress, then you need to set `shouldSetActiveChannel` to `false` ([docs](https://getstream.io/chat/docs/sdk/angular/services/ChannelService/#init))

**Comment by ilyakonrad** [comment]
>you need to deselect the previous active channel

This is exactly what I needed, thanks, it helped!

Now I see the empty state while loading messages. I would expect some sort of loader, but that's on me to implement I guess.
![image](https://github.com/GetStream/stream-chat-angular/assets/25200186/a1696c9f-4f76-4e29-b8f5-3ff8d042d1ea)
