### ISSUE TITLE
Allow pasting images with ctrl + v

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#627]
Just got a request to support attaching images through `ctrl + v` which could help use images in chats quicker by not having to download them.

**Comment by szuperaz** [comment]
I agree, this makes sense. I can't give you an ETA, I'll try to implement this in the second half of September, but it might get pushed to Q4.

In the meantime, you can try to build this yourself, but it requires some DOM API queries into the internals of SDK components which can hurt maintainability:
- Watch for clipboard paste events
- Check if any of the `textarea` element inside the `stream-message-input` component has the focus (thread vs channel message input) -> this is the hacky part
- Using Angular's DI, you can get the `AttachmentService` of the given `stream-message-input` component
- Use the `filesSelected` method of the `AttachmentService` to upload and create attachment from an image file

**Comment by ilyakonrad** [comment]
Thanks a lot, I'll wait for the official implementation ☺️

**Comment by ilyakonrad** [comment]
@szuperaz It seems to have broken pasting of text.

**Comment by ilyakonrad** [comment]
Nevermind, works in the latest version.
