### ISSUE TITLE
Mobile view UX improvements

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#638]
In version 4 stream chat angular seemed to have handled the usual mobile view layout changes requirement internally, by _adding_ class `str-chat-channel-list--open` to `.str-chat-channel-list` whenever the burger menu was clicked, and then _removing_ it when a channel was selected or user clicked outside.

There was also a bug with "load more" button, which triggered the removal of the class when you clicked on the text. It appears that click on the "load more" text doesn't pass [the check](https://github.com/GetStream/stream-chat-angular/blob/4.x.x/projects/stream-chat-angular/src/lib/channel-list/channel-list-toggle.service.ts#L69), since it is immediately replaced by the loader. I face the same issue in v5 with my custom clickOutside directive which has a similar check.

In version 5 according to the docs devs have to implement their own "isMenuOpen" logic, but that creates shortcomings: how do you "close the menu" when clicked on the channel tile and not close it when clicked on "load more" or any empty space _inside_ of the channel list component?

Also, how do you combine it with tracking clicks outside of the channel list which should also "close" the menu? Ok, click outside is simple: create a directive that tracks clicks outside of the host element. But all the other issues remain, since in the docs it is suggested to just track all clicks on `stream-channel-list` element and close the menu on all of them.

One option is to manually check click target, classnames and so on, but that's not reliable: classes change, structure changes.
Another option would be to track channel change. Is there a way to do so?

How can I solve it? Also, why was this logic removed in v5? Thanks.

v4
https://github.com/user-attachments/assets/67a7717a-bdc8-45a3-b6e0-59466fe943ee

**Comment by szuperaz** [comment]
Hi,

We removed that service because we want to ship UI components, not layouts. It's more flexible if you can create your own layouts.

The way you can prevent closing the message menu when the "Load more" button was clicked is to check if there is an ongoing channel query:

```ts
closeMenu() {
  let isChannelQuieryInProgress = false;
  this.channelService.channelQueryState$.pipe(take(1)).subscribe((state) => {
    if (state?.state === 'in-progress') {
      isChannelQuieryInProgress = true;
    }
  });
  if (!isChannelQuieryInProgress) {
    this.isMenuOpen = false;
  }
}
```

Let me know if this doesn't solve your issue.

**Comment by ilyakonrad** [comment]
Thanks, it works.
What about reacting to the initialization of the channel? Wanna avoid doing this:
```
onChannelListClick(event: Event): void {
  if ((event.target as HTMLElement).closest('.str-chat__channel-preview')) {
    this.isMenuOpen = false
  }
}
```

**Comment by szuperaz** [comment]
Can you please expand what do you mean by "initialization of the channel"?

**Comment by ilyakonrad** [comment]
I want to close the channel list only when clicking outside of it or when clicking on the channel preview.

For the first requirement I'm using my clickOutside directive with your hack covering the click on the "load more" text.

```
<stream-channel-list
  class="channel-list"
  [class.channel-list--open]="isMenuOpen"
  (click)="onChannelListClick($event)"
  appClickOutside
  (clickOutside)="onClickOutside()"
></stream-channel-list>
```

```
// Triggered also when clicking on the "load more" button text.
onClickOutside(): void {
  let isChannelQueryInProgress = false
  this.channelService.channelQueryState$.pipe(take(1)).subscribe((state) => {
    if (state?.state === 'in-progress') {
      isChannelQueryInProgress = true
    }
  })

  if (!isChannelQueryInProgress) {
    this.isMenuOpen = false
  }
}

onChannelListClick(event: Event): void {
  if ((event.target as HTMLElement).closest('.str-chat__channel-preview')) {
    this.isMenuOpen = false
  }
}
```

Now I'd like to refactor onChannelListClick, so that I don't depend on library's html.

**Comment by szuperaz** [comment]
Maybe I'm missing something, but `onChannelListClick` implementation should be this:

```ts
let isChannelQueryInProgress = false
  this.channelService.channelQueryState$.pipe(take(1)).subscribe((state) => {
    if (state?.state === 'in-progress') {
      isChannelQueryInProgress = true
    }
  })

  if (!isChannelQueryInProgress) {
    this.isMenuOpen = false
  }
```
It will close the list on every click inside except for the "Load more" button. I think this is a reasonable implementation, but it will also close if someone clicks on an empty place.

If you want to prevent closing when a user clicks on an empty space I'd suggest to place the `stream-channel-list` inside your own `div`, and make your `div` `height: 100%`, and then the empty space will be outside of the `stream-channel-list` component. And then you can check if the click was inside your `div` or not. This should also make it easy to track outside clicks.

Let me know if you think I'm missing something.

**Comment by ilyakonrad** [comment]
You got it right, but yes, I don't want to close when clicked on an empty space inside of the list. So I'd only close when clicked outside or clicked on the preview directly.

Your solution with a wrapping div could work, but that would still close the list if I press between channel previews.

I know it's a minor detail, but I think it's worth the effort solving considering the UX improvement.
Misclicks/mistaps happen, and in this case if user didn't tap the button precisely and the list was closed, they might even start typing a message in a wrong chat if they didn't doublecheck the channel header.

**Comment by szuperaz** [comment]
The channel list doesn't have any empty space between the channel previews, but if you want to handle any possible future empty spaces, you can check if the click was inside the `stream-channel-preview` component, the component name is part of the SDK's public API, so it will only change as part of a breaking release (as opposed to a CSS class name):

```
closeMenu(event: Event) {
    if ((event.target as HTMLElement).closest('stream-channel-preview')) {
      this.isMenuOpen = false;
    }
  }
```

If you need something more custom, it's also fairly simple to create your own channel list using the built-in `stream-channel-preivew` component and the public API of the `ChannelService`.
