### ISSUE TITLE
Demo chat doesn't work

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#657]
I wanted to check the default styles for replies, since the demos on the main website are still using the older design.
But here https://angular-chat-demo-getstreamio.vercel.app/ it's either this or infinite loading.

![image](https://github.com/user-attachments/assets/c7b1b6b4-cd2e-4c14-a8f7-db5e8956d12b)

**Comment by szuperaz** [comment]
Thanks for reporting, the requests will sometimes timeout due to too many underlying test data. It's working now.
