### ISSUE TITLE
Links are rendered as text when not prefixed with http/https/www

### ISSUE THREAD

**Issue by ilyakonrad** [GetStream/stream-chat-angular#660]
![image](https://github.com/user-attachments/assets/15cfd60c-a841-4bc0-abd3-aaa16f1d2819)
![image](https://github.com/user-attachments/assets/c0a34888-c3eb-4b84-8e8d-86e05e4ab0d4)

**Comment by szuperaz** [comment]
Thanks for reporting this issue. It's already tracked in #612. I can't give an expected time for the fix, but you can subscribe to the other issue to be notified when it's fixed.
