### ISSUE TITLE
inviteMember should not automatically add member to channel

### ISSUE THREAD

**Issue by travisBradfield** [GetStream/stream-chat-angular#674]
I'm running the following method to **invite** members to an existing channel: 

`async inviteOnly() {
    console.log('💦💦 inviteOnly()');
    try {
      const channelId = this.channelService.activeChannel?.id;
      console.log('💦💦 inviteOnly() - channelId: ', channelId);
      const channel = this.chatService.chatClient.channel('messaging', channelId);
      const groupChatUsers = this.newGroupChatUsers.map(user => user.id);
      await channel.inviteMembers(groupChatUsers);
    } catch (error) {
      console.error('Invite only failed:', error);
    }
  }`
  
The problem is that the channel is joined automatically by the invite recipient. I want to give the recipient the opportunity to accept or reject this invitation. 

How do I update my method so that the inviteMembers() method does **not** automatically add the new members without accepting or rejecting the invite?

**Comment by szuperaz** [comment]
Whenever you invite someone to a channel, that someone will become a member - this is not something you can change, but you can find more info in our [API docs](https://getstream.io/chat/docs/javascript/channel_invites/)

However, invited users can still accept and reject the invite. It's also possible to only include a channel in the channel list once a user accepted the invite. All of that is covered in the Angular SDK's [channel invites guide](https://getstream.io/chat/docs/sdk/angular/code-examples/channel-invites/)

I'm going to close this ticket, but feel free to reopen it if you have any more questions.
